version: '3.9'

services:
  db_redis:
    image: redis:6.2.11-alpine
    env_file:
      - ./.env
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    volumes:
      - linebot-felice-volumes-redis:/data
    environment:
      - REDIS_CACHE=true
    networks:
      - linebot-felice-network

  linebot:
    image: zhima1mochi2:linebot-felice
    ports: 
      - "${LINEBOT_PORT}:${LINEBOT_PORT}"
    env_file:
      - ./.env
    environment:
      - CACHE_URL=db_redis:${CACHE_PORT}
    depends_on:
      - db_redis
    networks:
      - linebot-felice-network

networks:
  linebot-felice-network:
    driver: bridge

volumes:
  linebot-felice-volumes-redis:
    driver: local